version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Moscow
      - AUTO_UPDATE=true 
    volumes:
      - /usr/src:/config
      - /usr/src:/downloads
    ports:
      - 9116
    restart: unless-stopped
