version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /usr/src:/config
      - /usr/src:/downloads
    ports:
      - 9120:9120
    restart: unless-stopped
